"""empty message

Revision ID: 2dd703deee99
Revises: 48845cae5e6d
Create Date: 2024-07-29 17:58:09.185816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd703deee99'
down_revision = '48845cae5e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aspect_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_hero_aspect_id'), ['aspect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hero_phase_id'), ['phase_id'], unique=False)
        batch_op.create_foreign_key(None, 'phase', ['phase_id'], ['id'])
        batch_op.create_foreign_key(None, 'aspect', ['aspect_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_hero_phase_id'))
        batch_op.drop_index(batch_op.f('ix_hero_aspect_id'))
        batch_op.drop_column('aspect_id')
        batch_op.drop_column('phase_id')

    # ### end Alembic commands ###
