"""empty message

Revision ID: 48845cae5e6d
Revises: e2ca707c165f
Create Date: 2024-07-29 17:55:08.145135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48845cae5e6d'
down_revision = 'e2ca707c165f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aspect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aspect_name'), ['name'], unique=True)

    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_name'))

    op.drop_table('hero')
    with op.batch_alter_table('aspect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aspect_name'))

    op.drop_table('aspect')
    # ### end Alembic commands ###
