"""Add Aspect colours

Revision ID: 9e5303733c9d
Revises: f55252d4f593
Create Date: 2026-04-14 21:28:00.536970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e5303733c9d'
down_revision = 'f55252d4f593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aspect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fg_colour', sa.String(length=7), nullable=False, server_default='#000000'))
        batch_op.add_column(sa.Column('bg_colour', sa.String(length=7), nullable=False, server_default='#ffffff'))

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=mysql.ENUM('WIN', 'LOSS'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=mysql.ENUM('WIN', 'LOSS'),
               nullable=True)

    with op.batch_alter_table('aspect', schema=None) as batch_op:
        batch_op.drop_column('bg_colour')
        batch_op.drop_column('fg_colour')

    # ### end Alembic commands ###
