"""empty message

Revision ID: e2ca707c165f
Revises: c965a04ab25a
Create Date: 2024-07-28 10:37:28.224391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ca707c165f'
down_revision = 'c965a04ab25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('villain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('villain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_villain_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_villain_phase_id'), ['phase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('villain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_villain_phase_id'))
        batch_op.drop_index(batch_op.f('ix_villain_name'))

    op.drop_table('villain')
    # ### end Alembic commands ###
